### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by p5panam** [vanhoefm/krackattacks#11]
According to the video, attacking device must also be logged first on the wifi network, and the target also.
Re-routing packets is very old trick
https://lirias.kuleuven.be/bitstream/123456789/547640/1/usenix2016-wifi.pdf

Also from 2016 -- Nonce-Disrespecting Adversaries: Practical
Forgery Attacks on GCM in TLS
https://eprint.iacr.org/2016/475.pdf

Check against Chrome Canary MITM detection
https://www.bleepingcomputer.com/news/security/google-chrome-will-soon-warn-you-of-software-that-performs-mitm-attacks/

Decryption of WEP and WAP
https://github.com/ICSec/pyDot11

Only very few devices are vulnerable.

**Comment by simos** [comment]
There is a new paper from 2017, _Key Reinstallation Attacks: Forcing Nonce Reuse in WPA2_,
available at https://www.krackattacks.com/#paper 
It vastly changes what was known in 2016.

**Comment by vanhoefm** [comment]
These remarks don't make any sense?
