### ISSUE TITLE
Code to test vulneratibility

### ISSUE THREAD

**Issue by p5panam** [vanhoefm/krackattacks#26]
https://github.com/vanhoefm/krackattacks-test-ap-ft

**Comment by steev** [comment]
Don't suppose you could go back through and fix up the markdown modifications.  A great number of people are interested in how to test that they are vulnerable.

**Comment by soxrok2212** [comment]
Or perhaps open your own repository to host the code 👍

**Comment by p5panam** [comment]
https://github.com/vanhoefm/krackattacks-test-ap-ft

**Comment by probitious** [comment]
Awesome!

**Comment by bogy007** [comment]
Hi, 
ur YouTube account was terminated because of the video??

**Comment by vanhoefm** [comment]
https://github.com/vanhoefm/krackattacks-test-ap-ft

**Comment by vanhoefm** [comment]
Let's use my repo that was already online. Once place, there all the code can be.
