### ISSUE TITLE
vulnerability note VU#228519 link broken

### ISSUE THREAD

**Issue by sighmon** [vanhoefm/krackattacks#5]
> You can also read [vulnerability note VU#228519](https://www.kb.cert.org/vuls/id/228519) of CERT/CC for additional details on which products are known to be affected.

Link returns: 
```
Error 404
HTTP Web Server: IBM Notes Exception - Entry not found in index
```

**Comment by vanhoefm** [comment]
It seems CERT/CC has not yet made their vulnerability note public, hence why the link fails.

**Comment by Farandas** [comment]
**Waiting.**..  :)

**Comment by atipaHy** [comment]
The link is working now.
